trigger:
- main

pool:
  vmImage: 'windows-latest'

stages:
- stage: Build
  jobs:
  - template: pipelines/stages/build-stage-sql-artifact.yml
    parameters:
      path: "$(System.DefaultWorkingDirectory)\\Views"
      match: "*.sql"
      outPath: "$(System.DefaultWorkingDirectory)\\Combined\\Functions"
      outName: "UTIL.sql"
      pool: 
        vmImage: 'windows-latest'

- stage: Deploy
  dependsOn: Build
  condition: succeeded()
  jobs:
  - template: pipelines/stages/deploy-to-serverless-db.yml\
    parameters:
      path: "$(System.DefaultWorkingDirectory)\\Views"
      match: "*.sql"
      outPath: "$(System.DefaultWorkingDirectory)\\Combined\\Functions"
      outName: "UTIL.sql"
      pool: 
        vmImage: 'windows-latest'