trigger:
  - main

pool:
  vmImage: "windows-latest"

variables:
  # path: "$(System.DefaultWorkingDirectory)\\Views"
  match: "*.sql"
  outPath: "$(System.DefaultWorkingDirectory)\\Combined\\Functions"
  outName: "UTIL.sql"
  artifactName: compiledSQL
  artifactLocation: $(System.DefaultWorkingDirectory)

stages:
  - stage: Build
    jobs:
      - template: pipelines/stages/build-stage-sql-artifact.yml
        parameters:
          path: "$(System.DefaultWorkingDirectory)\\Views"
          match: ${{variables.match}}
          outPath: ${{variables.outPath}}
          outName: ${{variables.outName}}
          artifactName: ${{variables.artifactName}}
          artifactLocation: ${{variables.artifactLocation}}
          pool:
            vmImage: "windows-latest"

  - stage: Deploy
    dependsOn: Build
    condition: succeeded()
    jobs:
      - template: pipelines/stages/deploy-to-serverless-db.yml\
        parameters:
          path: "$(System.DefaultWorkingDirectory)\\Views"
          match: ${{variables.match}}
          outPath: ${{variables.outPath}}
          outName: ${{variables.outName}}
          artifactName: ${{variables.artifactName}}
          artifactLocation: ${{variables.artifactLocation}}
          pool:
            vmImage: "windows-latest"
