trigger:
- test2

pool:
  vmImage: 'windows-latest'

stages:
  - stage: build
    jobs:
    - job: run_build
      pool:
        vmImage: 'windows-latest'

      steps:
        - task: CopyFiles@2
          displayName: 'Copy scripts'
          inputs:
            contents: 'scripts/**'
            targetFolder: '$(Build.ArtifactStagingDirectory)'

        - publish: '$(Build.ArtifactStagingDirectory)/scripts'
          displayName: 'Publish script'
          artifact: sql-drop

  - stage: release
    dependsOn: build
    jobs:
    - job: deploy_sql
      pool:
        vmImage: 'windows-latest'
      steps:
      - download: current
        artifact: sql-drop
      - task: PowerShell@2
        displayName: 'Run SQL Scripts'
        inputs: 
          targetType: 'inline'
          script: |
            $files = Get-ChildItem -Path $(Pipeline.Workspace)\sql-drop -Filter *.sql -File
            foreach ($file in $files) {
              echo "Invoking SQL for $file.FullName ..."
              Invoke-Sqlcmd -InputFile $file.FullName -ServerInstance '$(SQLPoolEndpoint)' -Database '$(DestinationDB)' -Username '$(SQLPoolUser)' -Password '$(SQLPoolpw)' -QueryTimeout 36000 -Verbose
            }
