jobs:
- job: build
  displayName: Build SQL Artifact
  continueOnError: false
  pool: ${{parameters.pool}}

  steps:
  # Create Output Folder
  - template: steps/create-output-folder.yml

  #Process Files
  - template: steps/process-files.yml
    parameters: 
      path: ${{parameters.path}}
      match: ${{parameters.match}}
      
  # Combine SQL files
  - template: steps/combine-sql-files.yml
    parameters: 
      outPath: ${{parameters.outPath}}
      outName: ${{parameters.outName}}
      path: ${{parameters.path}}
      match: ${{parameters.match}}

  # Publish Artifact
  - template: steps/publish-artifact.yml
    parameters: 
      outPath: ${{parameters.outPath}}
      outName: ${{parameters.outName}}