jobs:
- job: build
  displayName: Build SQL Artifact
  continueOnError: false
  pool: ${{parameters.pool}}

  steps:
  # Create Output Folder
  - template: steps/create-output-folder.yml

  # List Files to Process
  - template: steps/list-files-to-process.yml
    parameters: 
      path: ${{parameters.path}}
      match: ${{parameters.match}}

  # Combine SQL files
  - template: steps/combine-sql-files.yml
    parameters: 
      outPath: ${{parameters.outPath}}
      outName: ${{parameters.outName}}
      path: ${{parameters.path}}
      match: ${{parameters.match}}

  # Publish Artifact
  - template: steps/publish-artifact.yml
    parameters: 
      outPath: ${{parameters.outPath}}
      outName: ${{parameters.outName}}

  #---
  # Run SQL Scripts
  - template: steps/run-sql-scripts.yml
    parameters:
      outPath: ${{parameters.outPath}}
      outName: ${{parameters.outName}}
      path: ${{parameters.path}}
      match: ${{parameters.match}}
  
  # Delete Combined SQL Files File
  - template: steps/delete-files.yml
    parameters:
      outPath: ${{parameters.outPath}}
      outName: ${{parameters.outName}}
      path: ${{parameters.path}}
      match: ${{parameters.match}}